// OpenCV CPU baseline features

#define CV_CPU_COMPILE_SSE 1
#define CV_CPU_BASELINE_COMPILE_SSE 1

#define CV_CPU_COMPILE_SSE2 1
#define CV_CPU_BASELINE_COMPILE_SSE2 1

#define CV_CPU_COMPILE_SSE3 1
#define CV_CPU_BASELINE_COMPILE_SSE3 1

#define CV_CPU_COMPILE_SSE4_1          1
#define CV_CPU_COMPILE_SSE4_2          1
#define CV_CPU_COMPILE_POPCNT          1
#define CV_CPU_COMPILE_AVX             1
#define CV_CPU_COMPILE_AVX2            1
#ifndef NO_AVX512
#define CV_CPU_COMPILE_AVX_512F        1
#define CV_CPU_COMPILE_AVX512_COMMON   1
#define CV_CPU_COMPILE_AVX512_SKX      1
#endif NO_AVX512
#if 0
#define CV_CPU_COMPILE_AVX512_KNL      1
#define CV_CPU_COMPILE_AVX512_KNM      1
#define CV_CPU_COMPILE_AVX512_CNL      1
#define CV_CPU_COMPILE_AVX512_CLX      1
#define CV_CPU_COMPILE_AVX512_ICL      1
#endif

#define CV_CPU_BASELINE_FEATURES 0 \
    , CV_CPU_SSE \
    , CV_CPU_SSE2 \
    , CV_CPU_SSE3 \


// OpenCV supported CPU dispatched features

#define CV_CPU_DISPATCH_COMPILE_SSE4_1 1
#define CV_CPU_DISPATCH_COMPILE_SSE4_2 1
#define CV_CPU_DISPATCH_COMPILE_FP16 1
#define CV_CPU_DISPATCH_COMPILE_AVX 1
#define CV_CPU_DISPATCH_COMPILE_AVX2 1
#ifndef NO_AVX512
#define CV_CPU_DISPATCH_COMPILE_AVX512_SKX 1
#define CV_CPU_AVX512_CONDITIONAL , CV_CPU_AVX512_SKX
#else
#define CV_CPU_AVX512_CONDITIONAL
#endif

#define CV_CPU_DISPATCH_FEATURES 0 \
    , CV_CPU_SSE4_1 \
    , CV_CPU_SSE4_2 \
    , CV_CPU_FP16 \
    , CV_CPU_AVX \
    , CV_CPU_AVX2 \
      CV_CPU_AVX512_CONDITIONAL
//  ^^^ no "," coma here
